#### **1. Mathematical Operations**

##### 1. Create two NumPy arrays of shape (3, 3) and perform element-wise addition, subtraction, multiplication, and division.

In [2]:
import numpy as np

arr1 = np.array([[1, 2, 3], [4, 5 ,6], [7, 8, 9]])
arr2 = np.array([[9, 8, 7], [6, 5, 4], [3, 2, 1]])

print("array 1 : ",arr1)
print("Array 2 : ",arr2)
print("Addition : ",arr1 + arr2)
print("Subtraction : ",arr1 -arr2)
print("Multiplication : ",arr1 * arr2)
print("Division : ",arr1 / arr2)

array 1 :  [[1 2 3]
 [4 5 6]
 [7 8 9]]
Array 2 :  [[9 8 7]
 [6 5 4]
 [3 2 1]]
Addition :  [[10 10 10]
 [10 10 10]
 [10 10 10]]
Subtraction :  [[-8 -6 -4]
 [-2  0  2]
 [ 4  6  8]]
Multiplication :  [[ 9 16 21]
 [24 25 24]
 [21 16  9]]
Division :  [[0.11111111 0.25       0.42857143]
 [0.66666667 1.         1.5       ]
 [2.33333333 4.         9.        ]]


##### 2. Generate a NumPy array with random integers and apply square root, exponential, and logarithmic functions.

In [6]:
arr1 = np.array([1, 2, 3, 4 , 5, 6, 7])

print("Array : ",arr1)

print("Square root :",np.sqrt(arr1))
print("exponential :",np.exp(arr1))
print("logarithmic :",np.log(arr1))

Array :  [1 2 3 4 5 6 7]
Square root : [1.         1.41421356 1.73205081 2.         2.23606798 2.44948974
 2.64575131]
exponential : [   2.71828183    7.3890561    20.08553692   54.59815003  148.4131591
  403.42879349 1096.63315843]
logarithmic : [0.         0.69314718 1.09861229 1.38629436 1.60943791 1.79175947
 1.94591015]


##### 3. Create a NumPy array and apply trigonometric operations like sin, cos, and tan.

In [7]:
array = np.array([0, 30, 45, 60, 90])

print("array : ",array)

print("sin : ",np.sin(array))
print("cos : ",np.cos(array))
print("tan : ",np.tan(array))


array :  [ 0 30 45 60 90]
sin :  [ 0.         -0.98803162  0.85090352 -0.30481062  0.89399666]
cos :  [ 1.          0.15425145  0.52532199 -0.95241298 -0.44807362]
tan :  [ 0.         -6.4053312   1.61977519  0.32004039 -1.99520041]


##### 4. Normalize a NumPy array using vectorized operations (subtract mean and divide by std).

In [9]:
array = np.array([10, 20, 30, 40, 50])

print("array : ", array)

mean_array = np.mean(array)
std_array = np.std(array)

normalized_array = (array - mean_array) / std_array

print("Normalized array : ",normalized_array)

array :  [10 20 30 40 50]
Normalized array :  [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


##### 5. Implement a function using NumPy that calculates the Euclidean distance between two points.

In [10]:
import numpy as np

def euclidean_distance_norm(p1, p2):
    return np.linalg.norm(np.array(p1) - np.array(p2))

point_a = [1, 2, 3]
point_b = [4, 5, 6]

dist = euclidean_distance_norm(point_a, point_b)
print(f"Euclidean Distance: {dist}")


Euclidean Distance: 5.196152422706632


#### **2. Combining and Splitting Arrays**

##### 1. Create two 1D arrays and concatenate them horizontally and vertically.

In [17]:
array1 = np.array([1, 2, 3,4 ,5])
array2 = np.array([6, 7, 8 ,9, 10])

print("Array 1 : \n",array1)
print("Array 2 : \n",array2)
print("Horizontally Array : \n",np.hstack((array1,array2)))
print("Vertically Array : \n",np.vstack((array1, array2)))

Array 1 : 
 [1 2 3 4 5]
Array 2 : 
 [ 6  7  8  9 10]
Horizontally Array : 
 [ 1  2  3  4  5  6  7  8  9 10]
Vertically Array : 
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


##### 2. Stack multiple 2D arrays using vstack and hstack and then split them back using vsplit and hsplit.

In [26]:
import numpy as np

A = np.array([[1, 2],
              [3, 4]])

B = np.array([[5, 6],
              [7, 8]])

print("--- Vertical Stacking & Splitting ---")
v_stacked = np.vstack((A, B))
print("vstack result:\n", v_stacked)


A_v, B_v = np.vsplit(v_stacked, 2)
print("vsplit piece 1:\n", A_v)


print("\n--- Horizontal Stacking & Splitting ---")
h_stacked = np.hstack((A, B))
print("hstack result:\n", h_stacked)

A_h, B_h = np.split(h_stacked, 2, axis=1)
print("hsplit piece 1:\n", A_h)


--- Vertical Stacking & Splitting ---
vstack result:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]
vsplit piece 1:
 [[1 2]
 [3 4]]

--- Horizontal Stacking & Splitting ---
hstack result:
 [[1 2 5 6]
 [3 4 7 8]]
hsplit piece 1:
 [[1 2]
 [3 4]]


##### 3. Create a 2D array and split it into 4 equal sub-arrays.

In [30]:
arr = np.array([
        [1, 2, 3, 4],[5, 6 ,7, 8],[9, 10, 11, 12],[13, 14, 15, 16]
        ])

print("Original Array : \n",arr)

top, bottom = np.vsplit(arr, 2)

quad1, quad2 = np.hsplit(top, 2)
quad3, quad4 = np.hsplit(bottom, 2)

print("\n--- 4 Equal Quadrants ---")
print("Top-Left:\n", quad1)
print("Top-Right:\n", quad2)
print("Bottom-Left:\n", quad3)
print("Bottom-Right:\n", quad4)

Original Array : 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

--- 4 Equal Quadrants ---
Top-Left:
 [[1 2]
 [5 6]]
Top-Right:
 [[3 4]
 [7 8]]
Bottom-Left:
 [[ 9 10]
 [13 14]]
Bottom-Right:
 [[11 12]
 [15 16]]


##### 4. Demonstrate the difference between concatenate, stack, and hstack functions using 2D arrays.

In [58]:
array_2D = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
array_2D1 = np.array([[9, 10, 11, 12], [13, 14, 15, 16]])

print("1st 2D array :\n",array_2D)
print("2nd 2D array :\n",array_2D1)

print("Concatenated 2D array (axis=0) :\n",np.concatenate((array_2D, array_2D1), axis=0))

print("stack (Axis = 0):\n", np.stack((array_2D, array_2D1), axis=0))
print("stack (Axis = 1):\n", np.stack((array_2D, array_2D1), axis=1))

print("hstack :\n", np.hstack((array_2D, array_2D1)))

1st 2D array :
 [[1 2 3 4]
 [5 6 7 8]]
2nd 2D array :
 [[ 9 10 11 12]
 [13 14 15 16]]
Concatenated 2D array (axis=0) :
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
stack (Axis = 0):
 [[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[ 9 10 11 12]
  [13 14 15 16]]]
stack (Axis = 1):
 [[[ 1  2  3  4]
  [ 9 10 11 12]]

 [[ 5  6  7  8]
  [13 14 15 16]]]
hstack :
 [[ 1  2  3  4  9 10 11 12]
 [ 5  6  7  8 13 14 15 16]]


In [32]:
import numpy as np

arr_a = np.array([[1, 2],
                  [3, 4]])
arr_b = np.array([[5, 6],
                  [7, 8]])

print("Array A:\n", arr_a)
print("Array B:\n", arr_b)
print("\n-- np.concatenate --")

concat_axis0 = np.concatenate((arr_a, arr_b), axis=0)
print("Concatenate (axis=0):\n", concat_axis0)

concat_axis1 = np.concatenate((arr_a, arr_b), axis=1)
print("Concatenate (axis=1):\n", concat_axis1)

print("\n-- np.stack --")

stack_axis0 = np.stack((arr_a, arr_b), axis=0)
print("Stack (axis=0):\n", stack_axis0)
print("Shape of stack_axis0:", stack_axis0.shape)

stack_axis1 = np.stack((arr_a, arr_b), axis=1)
print("Stack (axis=1):\n", stack_axis1)
print("Shape of stack_axis1:", stack_axis1.shape)

print("\n-- np.hstack --")

h_stack = np.hstack((arr_a, arr_b))
print("HStack:\n", h_stack)

Array A:
 [[1 2]
 [3 4]]
Array B:
 [[5 6]
 [7 8]]

-- np.concatenate --
Concatenate (axis=0):
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]
Concatenate (axis=1):
 [[1 2 5 6]
 [3 4 7 8]]

-- np.stack --
Stack (axis=0):
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
Shape of stack_axis0: (2, 2, 2)
Stack (axis=1):
 [[[1 2]
  [5 6]]

 [[3 4]
  [7 8]]]
Shape of stack_axis1: (2, 2, 2)

-- np.hstack --
HStack:
 [[1 2 5 6]
 [3 4 7 8]]


##### 5. Create a 3D array and flatten it, then reshape it back to its original shape.

In [40]:
array_3D = np.array([[
      [1, 2, 3],
      [4, 5, 6],
      [7, 8, 9]
    ]])

print("Original array :\n", array_3D)

flatten = array_3D.flatten()

print("flatten array :\n", flatten)

reshape_array = flatten.reshape(3,3)

print("Original shape :\n", reshape_array)

Original array :
 [[[1 2 3]
  [4 5 6]
  [7 8 9]]]
flatten array :
 [1 2 3 4 5 6 7 8 9]
Original shape :
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


#### **3. Search, Sort, Aggregating/Statistical Functions**

##### 1. Create a NumPy array and find the index of the maximum and minimum elements.

In [41]:
array = np.array([[
    [1, 2, 3],
    [4, 5 ,6],
    [7, 8, 9]
]])

print("Original Array :\n",array)

print("Maximum element :\n",np.max(array))
print("Minimum element :\n",np.min(array))

Original Array :
 [[[1 2 3]
  [4 5 6]
  [7 8 9]]]
Maximum element :
 9
Minimum element :
 1


##### 2. Sort a 2D array along different axes and display the result.

In [43]:
array = np.array([
    [10, 40, 20, 30],
    [43, 55, 12, 47]
])

print("Original Array :\n",array)

print("Sorted Array veritcaliy :\n",np.sort(array, axis=0))
print("Sorted Array veritcaliy :\n",np.sort(array, axis=1))

Original Array :
 [[10 40 20 30]
 [43 55 12 47]]
Sorted Array veritcaliy :
 [[10 40 12 30]
 [43 55 20 47]]
Sorted Array veritcaliy :
 [[10 20 30 40]
 [12 43 47 55]]


##### 3. Generate a random NumPy array and find the mean, median, variance, and standard deviation.

In [45]:
array = np.array([[
    [1, 2, 3],
    [4, 5 ,6],
    [7, 8, 9]
]])

print("Original array:\n",array)

print("Mean :",np.mean(array))
print("Median :",np.median(array))
print("Variance :",np.var(array))
print("Standard Deviation :",np.std(array))

Original array:
 [[[1 2 3]
  [4 5 6]
  [7 8 9]]]
Mean : 5.0
Median : 5.0
Variance : 6.666666666666667
Standard Deviation : 2.581988897471611


##### 4. Use np.where to find all elements greater than a certain threshold in a given array.

In [52]:
arr1 = np.array([10, 30, 40, 50, 20, 80, 90, 12, 30])

print("Original Array:\n",arr1)

filter_array = np.where(arr1 >= 40, "Pass", "Fail")

print("Greater than 40 marks :\n",filter_array)




Original Array:
 [10 30 40 50 20 80 90 12 30]
Greater than 40 marks :
 ['Fail' 'Fail' 'Pass' 'Pass' 'Fail' 'Pass' 'Pass' 'Fail' 'Fail']


##### 5. Create a NumPy array and count how many elements are positive, negative, or zero.

In [60]:
import numpy as np

array = np.array([[
    [10, -20, -10],
    [0, 30, 40],
    [12, 0, 45]
]])

print("Original Array:\n",array)
positive_count = np.sum(array > 0)
negative_count = np.sum(array < 0)
zero_count = np.sum(array == 0)

print("Number of Positive elements :", positive_count)
print("Number of Negative elements :", negative_count)
print("Number of Zero elements :", zero_count)

Original Array:
 [[[ 10 -20 -10]
  [  0  30  40]
  [ 12   0  45]]]
Number of Positive elements : 5
Number of Negative elements : 2
Number of Zero elements : 2
