# **Task 1.1: Basic Filtering**

Create a NumPy array ages with the following values: [25, 30, 18, 35, 22, 40, 17].
Use boolean indexing to create a new array adults containing only the ages that are 18 or older.

In [9]:
import numpy as np

ages = np.array([25, 30, 18, 35, 22, 40, 17])

adults = ages[ages >= 18]

print("Adults Age : ",adults)

Adults Age :  [25 30 18 35 22 40]


**Task 1.2: Filtering with Multiple Conditions**

Using the ages array again, find the ages that are strictly greater than 20 AND strictly less than 35.

Store the result in a new array called young_adults.

In [10]:
ages = np.array([25, 30, 18, 35, 22, 40, 17])

young_abults = ages[(ages > 20) & (ages < 35)]

print("Young Abults : ",young_abults)

Young Abults :  [25 30 22]


Create a NumPy array names with the following values: ['Alice', 'Bob', 'Charlie', 'David', 'Eve'].

Use boolean indexing to select names that start with the letter 'A' or 'E'.

Hint: You might need to use string operations within your boolean condition.

In [11]:
array_names = np.array(['Alice', 'Bob', 'Charlie', 'David', 'Eve'])

names = array_names[np.char.startswith(array_names, 'A') | np.char.startswith(array_names, 'E')]

print(names)

['Alice' 'Eve']


**Task 2.1: Basic Masking for Selection**

Create a NumPy array temperatures with the following values: [28, 32, 25, 35, 30, 22, 38].

Create a boolean mask is_hot where True indicates temperatures above 30 degrees Celsius.

Use this mask to select the hot temperatures from the temperatures array.

In [12]:
array = np.array([28, 32, 25, 35, 30, 22, 38])

is_hot = array > 30

hot_temperatures = array[is_hot]

print("Is Hot : ",is_hot)

print("Hot Temperatures: ",hot_temperatures)

Is Hot :  [False  True False  True False False  True]
Hot Temperatures:  [32 35 38]


**Task 2.2: Masking for Modification**

Using the temperatures array again, use the is_hot mask to change all temperatures above 30 degrees Celsius to 31 degrees Celsius.

In [13]:
array[is_hot] = 31

print("Modifing Array : ",array)

Modifing Array :  [28 31 25 31 30 22 31]


**Task 2.3: Using np.where() for Masking**

Create a NumPy array scores with the following values: [65, 80, 72, 90, 55, 78].

Use np.where() to create a new array grades. If a score is 75 or above, the grade should be 'Pass', otherwise 'Fail'.

In [14]:
array_scores = np.array([65, 80, 72, 90, 55, 78])

grades = np.where(array_scores >= 75, 'Pass', 'Fail')

print("Grades : ",grades)

Grades :  ['Fail' 'Pass' 'Fail' 'Pass' 'Fail' 'Pass']


**Task 3.1: Reshaping a 1D array to 2D**

Create a 1D NumPy array numbers_1d with values from 1 to 12 (inclusive).

Reshape this array into a 2D array with 3 rows and 4 columns.

In [15]:
numbers_1d = np.array([1, 2, 3, 4, 5, 6, 7, 8 , 9, 10, 11, 12])

numbers_2d = numbers_1d.reshape(3, 4)

print("Original Array:\n",numbers_1d)
print("Reshaped Array:\n",numbers_2d)

Original Array:
 [ 1  2  3  4  5  6  7  8  9 10 11 12]
Reshaped Array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


**Task 3.2: Reshaping a 2D array to 1D (Flattening)**

Using the numbers_2d array from the previous task, flatten it back into a 1D array.

In [16]:
numbers_2d = np.array([
    [1, 2, 3 ,4 ,5],
    [6, 7 , 8, 9, 10]
])

flatten_array = numbers_2d.flatten()

print(flatten_array)

[ 1  2  3  4  5  6  7  8  9 10]


### **Task 3.3: Reshaping with `-1`**
#### Create a 1D NumPy array `values` with values from 1 to 15 (inclusive).
#### Reshape this array into a 2D array with 5 rows, letting NumPy automatically determine the number of columns.

---

In [20]:
array_1D = np.arange(1,16)

reshape_array_1D = array_1D.reshape(5,-1)

print("Original Array :\n",array_1D)

print("Reshape Array :\n",reshape_array_1D)

Original Array :
 [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
Reshape Array :
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]]


### **Task 4.1: Broadcasting a Scalar to an Array**
#### Create a NumPy array `prices` with the following values: `[10, 20, 30]`.
#### Increase all prices by 5 using broadcasting.


In [21]:
array_prices = np.array([10, 20, 30])

add_prices = array_prices + 5

print("Original Array : ", array_prices)

print("Array Add 5 of each elements : ",add_prices)

Original Array :  [10 20 30]
Array Add 5 of each elements :  [15 25 35]


### **Task 4.2: Broadcasting a 1D Array to a 2D Array (Row-wise)**
#### Create a 2D NumPy array `sales` representing sales figures for 3 products over 2 days:
#### ```
#### [[10, 20],
####  [15, 25],
####  [12, 18]]
#### ```
#### Create a 1D NumPy array `bonuses` representing bonuses for each product: `[2, 3, 1]`.
#### Add the `bonuses` array to the `sales` array, broadcasting row-wise.

In [27]:
array_2D = np.array([
    [10,20],
    [15,25],
    [12,18]
])

array_1D = ([2, 3, 1])

vertical_array_1D = np.vstack(array_1D)

print("Original 2D Array :\n",array_2D)

print("Original 1D Array :\n",array_1D)

print("vertical 1D array :\n",vertical_array_1D)

bounses = array_2D + vertical_array_1D

print("1D and 2D Array sum :\n",bounses)

Original 2D Array :
 [[10 20]
 [15 25]
 [12 18]]
Original 1D Array :
 [2, 3, 1]
vertical 1D array :
 [[2]
 [3]
 [1]]
1D and 2D Array sum :
 [[12 22]
 [18 28]
 [13 19]]


### **Task 4.3: Broadcasting a 1D Array to a 2D Array (Column-wise)**
#### Using the `sales` array again, create a 1D NumPy array `tax_rates` representing tax rates for each day: `[0.1, 0.05]`.
#### Calculate the tax amount for each sale by multiplying the `sales` array with the `tax_rates` array, broadcasting column-wise.

In [40]:
tax_rates = np.array([0.1, 0.05])

tax_amount = bounses + (tax_rates*10)
print("After tax amount :\n",tax_amount)

After tax amount :
 [[13.  22.5]
 [19.  28.5]
 [14.  19.5]]
